import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {

  const [timeLeft, setTimeLeft] = useState({})

  const calculateTimeLeft = () => {
    const firstGame: any = new Date('2/24/2023')
    const rightNow: any = new Date()
    let difference: number = firstGame - rightNow
    let timeLeft = {}

    if (difference > 0) {
      timeLeft = {
        days: Math.floor(difference / (1000 * 60 * 60 * 24)),
        hours: Math.floor((difference / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((difference / 1000 / 60) % 60),
        seconds: Math.floor((difference / 1000) % 60)
      };
    }
    return timeLeft
  }

  useEffect(() => {
    const interval = setInterval(() => {
      const ret = calculateTimeLeft()
      setTimeLeft(ret)
    }, 1000)
    return () => clearInterval(interval)
  }, [])


  return (
    <div>
      <Head>
        <title>Countdown Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="p-12 text-center font-['Phillies'] text-5xl">Phirst game in</h1>
      <main className="grid grid-cols-4 gap-1 place-items-center">
        <div>
          <div className="text-2xl box-border bg-retro-red p-4 rounded border-2">
            <h1>{JSON.stringify(Object.values(timeLeft)[0])}</h1>
          </div>
          <h4 className="p-2 text-lg text-center">days</h4>
        </div>

        <div>
          <div className="text-2xl text-center bg-powder-blue box-border #6F263D p-4 rounded border-2">
            <h1>{JSON.stringify(Object.values(timeLeft)[1])}</h1>
          </div>
          <h4 className="p-2 text-lg text-center">hours</h4>
        </div>

        <div>
          <div className="text-2xl text-center bg-retro-red box-border #6F263D p-4 rounded border-2">
            <h1>{JSON.stringify(Object.values(timeLeft)[2])}</h1>
          </div>
          <h4 className="p-2 text-lg text-center">minutes</h4>
        </div>
        
        <div>
          <div className="text-2xl text-center bg-powder-blue box-border #6F263D p-4 rounded border-2">
            <h1>{JSON.stringify(Object.values(timeLeft)[3])}</h1>
          </div>
          <h4 className="p-2 text-lg text-center">seconds</h4>
        </div>
      </main>
    </div>
  )
}
